const GET_ALL_REVENUE = 'GET_ALL_REVENUE';
const FETCH_GET_ALL_REVENUE = 'FETCH_GET_ALL_REVENUE';
const RESET_REVENUE = 'RESET_REVENUE';
const GET_ALL_REVENUE_BY_FILTER_DATE = 'GET_ALL_REVENUE_BY_FILTER_DATE';
const FETCH_GET_ALL_REVENUE_BY_FILTER_DATE = 'FETCH_GET_ALL_REVENUE_BY_FILTER_DATE';

export default {
    GET_ALL_REVENUE: GET_ALL_REVENUE,
    FETCH_GET_ALL_REVENUE: FETCH_GET_ALL_REVENUE,
    RESET_REVENUE: RESET_REVENUE,
    GET_ALL_REVENUE_BY_FILTER_DATE: GET_ALL_REVENUE_BY_FILTER_DATE,
    FETCH_GET_ALL_REVENUE_BY_FILTER_DATE: FETCH_GET_ALL_REVENUE_BY_FILTER_DATE
}