const GET_FOOD_BY_CATEGORY = 'GET_FOOD_BY_CATEGORY';
const FETCH_FOOD_BY_CATEGORY = 'FETCH_FOOD_BY_CATEGORY';
const GET_ALL_FOOD = 'GET_ALL_FOOD';
const FETCH_ALL_FOOD = 'FETCH_ALL_FOOD';
const RESET_FOOD = 'RESET_FOOD';
const FETCH_ALL_FOOD_BY_FILTER = 'FETCH_ALL_FOOD_BY_FILTER';

export default {
    GET_FOOD_BY_CATEGORY: GET_FOOD_BY_CATEGORY,
    FETCH_FOOD_BY_CATEGORY: FETCH_FOOD_BY_CATEGORY,
    GET_ALL_FOOD: GET_ALL_FOOD,
    FETCH_ALL_FOOD: FETCH_ALL_FOOD,
    RESET_FOOD: RESET_FOOD,
    FETCH_ALL_FOOD_BY_FILTER: FETCH_ALL_FOOD_BY_FILTER
}