const GET_ALL_BILL = 'GET_ALL_BILL';
const RESET_BILL = 'RESET_BILL';
const FETCH_GET_ALL_BILL = 'FETCH_GET_ALL_BILL';
const GET_ALL_BILL_BY_FILTER = 'GET_ALL_BILL_BY_FILTER';
const FETCH_GET_ALL_BILL_BY_FILTER = 'FETCH_GET_ALL_BILL_BY_FILTER';


export default {
    GET_ALL_BILL: GET_ALL_BILL,
    RESET_BILL: RESET_BILL,
    FETCH_GET_ALL_BILL: FETCH_GET_ALL_BILL,
    GET_ALL_BILL_BY_FILTER: GET_ALL_BILL_BY_FILTER,
    FETCH_GET_ALL_BILL_BY_FILTER: FETCH_GET_ALL_BILL_BY_FILTER
}