const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
const RESET_CATEGORY = 'RESET_CATEGORY';

export default {
    GET_ALL_CATEGORIES: GET_ALL_CATEGORIES,
    FETCH_ALL_CATEGORIES: FETCH_ALL_CATEGORIES,
    RESET_CATEGORY: RESET_CATEGORY
}