const ACCOUNT_SCHEMA_NAME = 'accounts';
const CATEGORY_SCHEME_NAME = 'categories';
const FOOD_SCHEMA_NAME = 'foods';
const TABLE_SCHEMA_NAME = 'tables';
const USERORDER_SCHEMA_NAME = 'userorders';
const BILL_SCHEMA_NAME = 'bills';
const REVENUE_SCHEMA_NAME = 'revenues';

module.exports = {
    ACCOUNT_SCHEMA_NAME: ACCOUNT_SCHEMA_NAME,
    CATEGORY_SCHEME_NAME: CATEGORY_SCHEME_NAME,
    FOOD_SCHEMA_NAME: FOOD_SCHEMA_NAME,
    TABLE_SCHEMA_NAME: TABLE_SCHEMA_NAME,
    USERORDER_SCHEMA_NAME: USERORDER_SCHEMA_NAME,
    BILL_SCHEMA_NAME: BILL_SCHEMA_NAME,
    REVENUE_SCHEMA_NAME: REVENUE_SCHEMA_NAME
}