const GET_ALL_TABLE = 'GET_ALL_TABLE';
const FETCH_ALL_TABLE = 'FETCH_ALL_TABLE';
const RESET_TABLE = 'RESET_TABLE';
const GET_INFO_TABLE_BY_TABLE = 'GET_INFO_TABLE_BY_TABLE';
const FETCH_INFO_TABLE_BY_TABLE = 'FETCH_INFO_TABLE_BY_TABLE';
const ORDER_FOOD = 'ORDER_FOOD';
const FETCH_ORDER_FOOD = 'FETCH_ORDER_FOOD';
const ADD_FOOD_FOR_BILL = 'ADD_FOOD_FOR_BILL';
const FETCH_ADD_FOOD_FOR_BILL = 'FETCH_ADD_FOOD_FOR_BILL';
const INCREMENT_COUNT_FOOD = 'INCREMENT_COUNT_FOOD';
const FETCH_INCREMENT_COUNT_FOOD = 'FETCH_INCREMENT_COUNT_FOOD';
const DECREMENT_COUNT_FOOD = 'DECREMENT_COUNT_FOOD';
const FETCH_DECREMENT_COUNT_FOOD = 'FETCH_DECREMENT_COUNT_FOOD';
const REMOVE_FOOD = 'REMOVE_FOOD';
const FETCH_REMOVE_FOOD = 'FETCH_REMOVE_FOOD';
const REMOVE_ALL_FOOD = 'REMOVE_ALL_FOOD';
const FETCH_REMOVE_ALL_FOOD = 'FETCH_REMOVE_ALL_FOOD';

export default {
    GET_ALL_TABLE: GET_ALL_TABLE,
    FETCH_ALL_TABLE: FETCH_ALL_TABLE,
    RESET_TABLE: RESET_TABLE,
    GET_INFO_TABLE_BY_TABLE: GET_INFO_TABLE_BY_TABLE,
    FETCH_INFO_TABLE_BY_TABLE: FETCH_INFO_TABLE_BY_TABLE,
    FETCH_ORDER_FOOD: FETCH_ORDER_FOOD,
    ORDER_FOOD: ORDER_FOOD,
    ADD_FOOD_FOR_BILL: ADD_FOOD_FOR_BILL,
    FETCH_ADD_FOOD_FOR_BILL: FETCH_ADD_FOOD_FOR_BILL,
    FETCH_INCREMENT_COUNT_FOOD: FETCH_INCREMENT_COUNT_FOOD,
    INCREMENT_COUNT_FOOD: INCREMENT_COUNT_FOOD,
    DECREMENT_COUNT_FOOD: DECREMENT_COUNT_FOOD,
    FETCH_DECREMENT_COUNT_FOOD: FETCH_DECREMENT_COUNT_FOOD,
    FETCH_REMOVE_FOOD: FETCH_REMOVE_FOOD,
    REMOVE_FOOD: REMOVE_FOOD,
    REMOVE_ALL_FOOD: REMOVE_ALL_FOOD,
    FETCH_REMOVE_ALL_FOOD: FETCH_REMOVE_ALL_FOOD,
    RESET_TABLE: RESET_TABLE
}